# Generated by Django 4.2 on 2023-04-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Roadtrip_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waypoint",
            name="latitue",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
